### PR TITLE
Pass editorOptions to correct prop in EditorEnvelope

### LINKED ISSUE #16: enable crop or remove button inside repeatable when using ImageInterface
I belief crop ist not supported inside the repeatable fields (correct me if I'm wrong but couldn't make it work), would it then be possible to remove the crop button with
```
          editorOptions:
            features:
              crop: false
```
 as it throws a Type Error when clicked

### PR DESCRIPTION
**Pull request by c4ll-m3-j4ck**
In `Envelope.js`, props were passed on to `EditorEnvelope` from neos-ui. Unfortunately, the props were not mapped correctly, `EditorEnvelope` expects `editorOptions` as `options`.

This fix maps the given `editorOptions` to the correct props in `EditorEnvelope`

Fixes #16

### CODE REVIEW

**Review by jonnitto — APPROVED** [review]

**Comment by jonnitto** [comment]
@mireo91 Can you merge this and create a new release?

**Review by mireo91 — APPROVED** [review]
just for consistency with Neos schema

**Review by mireo91 — APPROVED** [review]
the same

**Review by mireo91 — APPROVED** [review]
code looks good

**Comment by mireo91** [comment]
@jonnitto marge is done - new release will be this weekend, I hope - I will be in touch

**Pull request merged**
