### PR TITLE
Refactor package to pure function

### LINKED ISSUE #19: buttonAddLabel cant handle translations
the `buttonAddLabel` can't handle translation strings…

### PR DESCRIPTION
**Pull request by jonnitto**
- [x] Remove `plow-js` dependency
- [x] Update node to version 20
- [x] Translation for button label
- [x] Add default translations
- [x] Add nicer loading screen
- [x] Relay on the variables from Neos
- [x] Give editors more space (Many editors are optimized to the size of the sidebar, so we give them exactly that)
- [x] Add the option to hide the editor via `editorOptions.hidden` (This adds the possibillity to hide the whole editor based on data source)
- [x] Replace build webpack with esbuild
- [x] Integrate PR #26 
- [x] Add option for automatic sorting
- [x] More stable key index by adding an internal variable to value item. [Read more about it here](https://blog.anja-stricker.de/why-using-index-as-key-in-reactjs-map-function-can-cause-problems-and-how-to-fix-them) On commit, the value will be removed
- [x] Change cursor to `grab` and `grabbing` during move
- [x] Integrate `positional-array-sorter`

This will close #19, #27, #14 and #15

### CODE REVIEW

**Comment by jonnitto** [comment]
image

**Comment by jonnitto** [comment]
Xnapper-2024-10-13-14 30 50

**Comment by jonnitto** [comment]
image

**Comment by jonnitto** [comment]
Automatic sorting feature:


https://github.com/user-attachments/assets/75d1344b-44c2-4049-b55f-c6215fc6810c

**Comment by mireo91** [comment]
Wow I see there is a lot of amazing work done to make plugin better.
From what I can tell I have trust in you but I see that you from time to time make update of code but when you be sure then tell me then I will mere it to master branch and make new release for it

**Comment by jonnitto** [comment]
So, the `positional-array-sorter` is integrated. I would say **Ready for merge** 🎉

**Pull request merged**
